### ISSUE TITLE
Android timeout error 

### ISSUE THREAD

**Issue by halgurdkamal** [Fast-Solution-Inc/FastPay-Android-SDK#1] opened 2023-12-22 22:19 UTC
When opening Fastpay SDK, the app automatically redirects to the Fastpay App and returns an error code Activity.RESULT_CANCELED and the error message is timeout.

**Comment by zarrafAhmed** [comment] 2024-01-28 10:27
## Update: Issue Resolved in Fastpay SDK v1.0.1

We're pleased to announce that the issue encountered in the Fastpay SDK, where the app automatically redirected to the Fastpay App and returned an error code `Activity.RESULT_CANCELED` with the error message "timeout," has been successfully resolved in version 1.0.1.

### Details of the Fix:

- **Version:** Fastpay SDK v1.0.1
- **Resolved Issue:** 
   - Previously, when attempting to open the Fastpay SDK, the app unexpectedly redirected to the Fastpay App, resulting in an `Activity.RESULT_CANCELED` error and a "timeout" message.
   - This issue has now been addressed and resolved in the latest update.

### Recommended Action:

For all developers and users experiencing this problem, we recommend updating to Fastpay SDK version 1.0.1. This update provides a fix for the redirection and timeout issues, ensuring smoother and more reliable integration.

### How to Update:

1. Modify your project's dependency configuration to use Fastpay SDK v1.0.1.
2. Rebuild your project to ensure the updated SDK is properly integrated.

We apologize for any inconvenience caused by this issue and appreciate your patience as we worked on the fix. Thank you for your continued support and feedback, which are invaluable in helping us improve our services.

For further assistance or queries, feel free to reach out to our support team.

Thank you for using Fastpay SDK!

**Closed as completed by zarrafAhmed** 2024-01-28 10:27 UTC
